name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted
    # needs jq and platformio installed installed

    steps:
    - uses: actions/checkout@v2
    - name:  replace dummys with actual secrets 
      run: |
        sed -i 's/verySecretPassword/${{ secrets.WIFI_PASS }}/g' platformio.ini
        sed -i 's/niceWIFIName/${{ secrets.wifiSSID }}/g' platformio.ini
        sed -i 's/0000/${{ secrets.thingspeakChannelNumber }}/g' platformio.ini
        sed -i 's/ABCDEF/${{ secrets.thingspeakAPIKey }}/g' platformio.ini
        sed -i 's/1111/${{ secrets.thingspeakChannelNumberHigrow }}/g' platformio.ini
        sed -i 's/GHIJK/${{ secrets.thingspeakAPIKeyHigrow }}/g' platformio.ini

      
    - name: Run PlattformIO
      run: pio run -t upload
      

